version: '3.9'

services:
  # ------------------
  # Backend Service
  # ------------------
  backend:
    build:
      context: ./poker-backend
      dockerfile: Dockerfile
    container_name: poker-backend
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/poker
    depends_on:
      - db
    volumes:
      - ./poker-backend:/app

  # ------------------
  # Frontend Service
  # ------------------
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: poker-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    # volumes:
      # - ./frontend:/app

  # ------------------
  # PostgreSQL Database
  # ------------------
  db:
    image: postgres:15-alpine
    container_name: poker-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: poker
    ports:
      - "5432:5432"
    volumes:
      - poker-db-data:/var/lib/postgresql/data

# ------------------
# Named Volumes
# ------------------
volumes:
  poker-db-data:
