version: '3.8'

services:
  # The Database Service
  db:
    image: postgres:13-alpine
    container_name: poker-db
    environment:
      POSTGRES_DB: poker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - poker_data:/var/lib/postgresql/data

  # The Backend Service
  backend:
    build: ./backend
    container_name: poker-backend
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: poker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      # Use the Docker service name 'db' as the host
      DB_HOST: db 
    depends_on:
      - db

  # The Frontend Service
  frontend:
    build: ./frontend
    container_name: poker-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  poker_data: